[package]
name = "google-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"]}
colored = "3.0.0"
anyhow = "1.0.98"
base64 = "0.22.1"
url = { version = "2", features = ['serde']}
